# Generated by Django 6.0.1 on 2026-01-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_projeto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
